// Отдельный файл с плейлистом треков
window.myPlaylist = [
    { title: "А ночка тёмная была", src: "https://files.catbox.moe/xz5t2n.mp3" },
    { title: "Бабушкин дом", src: "https://files.catbox.moe/bx8ayy.mp3" },
	{ title: "Благодарность врагам", src: "https://files.catbox.moe/ba3p7d.mp3" },
    { title: "Болит душа", src: "https://files.catbox.moe/txa38k.mp3" },
    { title: "Вальс тополиного пуха", src: "https://files.catbox.moe/ghw2l4.mp3" },
    { title: "Весенний шансон", src: "https://files.catbox.moe/kjjlza.mp3" },
    { title: "Ветер бродяга", src: "https://files.catbox.moe/4uo8b5.mp3" },
    { title: "Волчья луна", src: "https://files.catbox.moe/d1kfss.mp3" },
    { title: "Воля гуляла", src: "https://files.catbox.moe/tz2ncb.mp3" },
	{ title: "Вперёд в СССР", src: "https://files.catbox.moe/qo7vg5.mp3" },
	{ title: "Гвоздей нету", src: "https://files.catbox.moe/w3w7u6.mp3" },
    { title: "Плачь гитара", src: "https://files.catbox.moe/0kfmwt.mp3" },
    { title: "Дедушкин с Бабушкой дом", src: "https://files.catbox.moe/qgyypd.mp3" },
    { title: "Деменция", src: "https://files.catbox.moe/ap6swi.mp3" },
    { title: "Душа", src: "https://files.catbox.moe/ceklqr.mp3" },
    { title: "Жизни поле-полюшко", src: "https://files.catbox.moe/3v16dd.mp3" },
    { title: "Идём по жизни", src: "https://files.catbox.moe/dj1jos.mp3" },	
    { title: "Я снова феникс", src: "https://files.catbox.moe/95b8pp.mp3" },
    { title: "К Деду с пивом", src: "https://files.catbox.moe/2narmt.mp3" },
	{ title: "Дворовый Воробей", src: "https://files.catbox.moe/crsc0a.mp3" },
    { title: "Жара сжигает всё", src: "https://files.catbox.moe/ybtx66.mp3" },
    { title: "Вишнёвая серёжка", src: "https://files.catbox.moe/yzxy0t.mp3" },
    { title: "Валиться из рук", src: "https://files.catbox.moe/pdtd7m.mp3" },
    { title: "Загуляло лето, загуляло", src: "https://files.catbox.moe/2ufu06.mp3" },
    { title: "Давление 200/120", src: "https://files.catbox.moe/0qlzvn.mp3" },
    { title: "Стар капитан", src: "https://files.catbox.moe/3g0zuw.mp3" },
	{ title: "Курсом мимо Шапито", src: "https://files.catbox.moe/m4wl9u.mp3" },
	{ title: "Не напишут стихов про меня", src: "https://files.catbox.moe/x2nvmj.mp3" },
    { title: "О человечности", src: "https://files.catbox.moe/egltya.mp3" },
    { title: "От безнаказаности", src: "https://files.catbox.moe/vvlbbr.mp3" },
    { title: "Прости Гагарин", src: "https://files.catbox.moe/3ix925.mp3" },
    { title: "Пыль на перстне", src: "https://files.catbox.moe/yi8egn.mp3" },
    { title: "Размышление о лени", src: "https://files.catbox.moe/rbexlj.mp3" },
    { title: "Сказать бы детям", src: "https://files.catbox.moe/mo4qym.mp3" }
    // Сюда можно добавлять новые песни через запятую:
    // { title: "Новая песня", src: "ссылка_на_mp3" },
];
